In [ ]:
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
!gdown --folder https://drive.google.com/drive/folders/1VCDwlUauxzXfW7B8XxzWdKfh9dbneMhr

Retrieving folder contents
Processing file 136gDA1TJRamND_N8_-K9zPrtNSGezOp3 Botanica_Premier.csv
Processing file 139wawJWPxfRcHaK_lZoyoiFSspiFQ9ZT DMA_Schema - Down.csv
Processing file 1c_iNQUyk1PHLr6s3Crbe8nRFFL1L3_-- Everich_I.csv
Processing file 17sH1pxMFzf99AsWfWEldwS2G1UK3HPbW Galaxy_9.csv
Processing file 17yDZiGJhkK-gLvHrJ43LoSS5DU3WcXIZ Golden_Mansion.csv
Processing file 1UYqbirZH7uxIcHXHg1NwhZ4ngzAD8XYJ Grand_Park.csv
Processing file 1Z__76IFNiA9Fw440RAeRfvlAHpYq1h0C Green_Bay.csv
Processing file 1RW_8iL61LkbI_ZNC0k82WfjpyT96RIFf HappyHomes_TrangCat.csv
Processing file 17_YNjO5Bzm6jLysA_86QCx-IJrgYuHPm Icon_56.csv
Processing file 1RgVFF6XcmOOL---ovLQHX7F6LtLvaB19 Kingston_Residence.csv
Processing file 1nmVT4lnbjrXkVDw7eQtPuR3szt_eMJ0c Lexington_Residence.csv
Processing file 1zrkYbVB9yA3062txEAASRSVzYv2MtVOQ Lucky_Dragon.csv
Processing file 1YgShNilFc5ltitnaTpn3NRf2pnB7ZP_b Millennium.csv
Processing file 1HYB4QUjjiYFPw6VEMUDJs9a79Kf-SIMw novaland_gardengate.csv
Processing file 1bnKKGT3KI6h353UzWQ808vZCxNV0DQo- novaland_luckypalace.csv
Processing file 171RSSuhAxfMpbLzk6-r3ouOOSTCWsxBl novaland_orchardgarden.csv
Processing file 1SSgmSrN_OgsnWh7-K0r0o7ml4bZtgMbe Orchard_Garden.csv
Processing file 1niX0yEccjahEIrFOVLV47dr9ItbdywiK RichStar.csv
Processing file 1E_WhTp3r_xfa2Eq7dYIt3Ka-I9tQwfGI River_Gate.csv
Processing file 1vQ94tAPlEKmw9KnUTR0KbrhFw8i59-bC Royal_City.csv
Processing file 1pQ1PQw_mAtcQ7ecjapUBrkG6CC6lxha6 Saigon_Royal.csv
Processing file 1__R1fLV_RXmzI0QaSDiLvSvr4bE9yg9S Sky_Lake.csv
Processing file 1zTOmuC8bqZMbf4z-VkJBEyi1nia-otW_t--_22tw9-Q Sky_Park
Processing file 1mjnI_lKaNgYKSP50gKX936RJiEOL8-uB Sky_Park.csv
Processing file 1T6pk0dUyZOoK6MNOTl2wCDZcTpgsWBzc Sunrise_City.csv
Processing file 1KLuuY8Lv0JFwx8xkLlSebVONCKNTMk4T Sunrise_Cityview.csv
Processing file 1B6XfIxkJ59RMWFqoW4JUbMcy80hna6vl Symphony.csv
Processing file 1GA0tAb4Iy3Qv0DPstKJ_9L6S1_lpJ_nO The_Botanica.csv
Processing file 1DhFs5PJa9Gba6LK_3kUV2IGT5vQdimiy The_EverRich_Infinity.csv
Processing file 1YpsK2498txjrxiDmrvjETPUmHIPT6CEh The_Grand_Manhattan.csv
Processing file 1xWZqASgNEzMt0C0zTJlaGmEPZ64kZE9T The_Prince_Residence.csv
Processing file 1NL0Ngg9paY4j747Hfj6tVnDcF5lR0wou The_Tresor.csv
Processing file 1RygfUZqfT8MANUHL7qmLoEVCBJTrjywJ Times_City.csv
Processing file 182Gl4Xsrm-ebRVUj8jwcdTUtrEkmTcrd Vinhomes_Bắc_Ninh.csv
Processing file 1djqPdaTHYwTmjlsBRFfwe0bSQ-_ZWSYT Vinhomes_Centralpark.csv
Processing file 103dmVHExuf2PRQV0zTiGiGKvQG91EEq6 Vinhomes_DongKhoi.csv
Processing file 1bxJIBcGmziAEC5TX5WNcERh-505Qx7Aq vinhomes_gardenia.csv
Processing file 1XkSeoa0MfVBzIO0guNq5hTY8_NI72qFSMTi8p9lwEmc Vinhomes_Golden_River_Bason
Processing file 10NdPGiFw8QXIjXMCrLQDdKWgGK54KGLL Vinhomes_Golden_River_Bason.csv
Processing file 1SAn1Pq1_RD_vGJ7zk2YUgNNrMMzlcNo- vinhomes_greenparadise.csv
Processing file 19xg2Td3HVzx0oCEgaso98UzlOPhKw1iH Vinhomes_Metropolis.csv
Processing file 12j7qSCoa4jCTy7rMkpb3iMya2hU6T-79 vinhomes_nct.csv
Processing file 1vJH583MyrXHb5S7Wi_htIK_zGmEVV9SwUg1ETwpdo8k Vinhomes_Ocean_Park
Processing file 1lWbiN_NLE91eh5MfRgFIKSMeMN7LhyH9 Vinhomes_Ocean_Park.csv
Processing file 14-QfA2FU3M6gS13XT25TO3CSH8Lds-9G vinhomes_smartcity.csv
Processing file 1aCv4wML2dDcD8z7Q9inBrR8C8q2aJcn2yNNkpUGZ51M Vinhomes_Star_City
Processing file 1CmFMj_Ql0Z6BnQP1dmeMTtuR-0d4rChn Vinhomes_Star_City.csv
Processing file 1VGRjW1CgWKVJ6dkV3WsoTwBC_DYwA99m Vinhomes_West_Point.csv
Processing file 1vxMnIsqf3ytBTCJjoFdBoCbEABarHeZt Wilton_Tower.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=136gDA1TJRamND_N8_-K9zPrtNSGezOp3
To: /content/Batdongsan_raw_ver1/Botanica_Premier.csv
100% 73.0k/73.0k [00:00<00:00, 102MB/s]
Downloading...
From: https://drive.google.com/uc?id=139wawJWPxfRcHaK_lZoyoiFSspiFQ9ZT
To: /content/Batdongsan_raw_ver1/DMA_Schema - Down.csv
100% 6.09k/6.09k [00:00<00:00, 28.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1c_iNQUyk1PHLr6s3Crbe8nRFFL1L3_--
To: /content/Batdongsan_raw_ver1/Everich_I.csv
100% 6.55k/6.55k [00:00<00:00, 31.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=17sH1pxMFzf99AsWfWEldwS2G1UK3HPbW
To: /content/Batdongsan_raw_ver1/Galaxy_9.csv
100% 24.8k/24.8k [00:00<00:00, 88.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=17yDZiGJhkK-gLvHrJ43LoSS5DU3WcXIZ
To: /content/Batdongsan_raw_ver1/Golden_Mansion.csv
100% 37.3k/37.3k [00:00<00:00, 99.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1UYqbirZH7uxIcHXHg1NwhZ4ngzAD8XYJ
To: /content/Batdongsan_raw_ver1/Grand_Park.csv
100% 2.17M/2.17M [00:00<00:00, 11.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Z__76IFNiA9Fw440RAeRfvlAHpYq1h0C
To: /content/Batdongsan_raw_ver1/Green_Bay.csv
100% 31.5k/31.5k [00:00<00:00, 43.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RW_8iL61LkbI_ZNC0k82WfjpyT96RIFf
To: /content/Batdongsan_raw_ver1/HappyHomes_TrangCat.csv
100% 55.4k/55.4k [00:00<00:00, 70.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=17_YNjO5Bzm6jLysA_86QCx-IJrgYuHPm
To: /content/Batdongsan_raw_ver1/Icon_56.csv
100% 26.5k/26.5k [00:00<00:00, 81.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RgVFF6XcmOOL---ovLQHX7F6LtLvaB19
To: /content/Batdongsan_raw_ver1/Kingston_Residence.csv
100% 86.7k/86.7k [00:00<00:00, 108MB/s]
Downloading...
From: https://drive.google.com/uc?id=1nmVT4lnbjrXkVDw7eQtPuR3szt_eMJ0c
To: /content/Batdongsan_raw_ver1/Lexington_Residence.csv
100% 85.0k/85.0k [00:00<00:00, 78.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1zrkYbVB9yA3062txEAASRSVzYv2MtVOQ
To: /content/Batdongsan_raw_ver1/Lucky_Dragon.csv
100% 4.08k/4.08k [00:00<00:00, 20.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1YgShNilFc5ltitnaTpn3NRf2pnB7ZP_b
To: /content/Batdongsan_raw_ver1/Millennium.csv
100% 92.1k/92.1k [00:00<00:00, 71.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1HYB4QUjjiYFPw6VEMUDJs9a79Kf-SIMw
To: /content/Batdongsan_raw_ver1/novaland_gardengate.csv
100% 15.5k/15.5k [00:00<00:00, 55.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1bnKKGT3KI6h353UzWQ808vZCxNV0DQo-
To: /content/Batdongsan_raw_ver1/novaland_luckypalace.csv
100% 41.5k/41.5k [00:00<00:00, 75.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=171RSSuhAxfMpbLzk6-r3ouOOSTCWsxBl
To: /content/Batdongsan_raw_ver1/novaland_orchardgarden.csv
100% 28.5k/28.5k [00:00<00:00, 93.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SSgmSrN_OgsnWh7-K0r0o7ml4bZtgMbe
To: /content/Batdongsan_raw_ver1/Orchard_Garden.csv
100% 30.7k/30.7k [00:00<00:00, 101MB/s]
Downloading...
From: https://drive.google.com/uc?id=1niX0yEccjahEIrFOVLV47dr9ItbdywiK
To: /content/Batdongsan_raw_ver1/RichStar.csv
100% 51.3k/51.3k [00:00<00:00, 101MB/s]
Downloading...
From: https://drive.google.com/uc?id=1E_WhTp3r_xfa2Eq7dYIt3Ka-I9tQwfGI
To: /content/Batdongsan_raw_ver1/River_Gate.csv
100% 58.1k/58.1k [00:00<00:00, 103MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vQ94tAPlEKmw9KnUTR0KbrhFw8i59-bC
To: /content/Batdongsan_raw_ver1/Royal_City.csv
100% 52.3k/52.3k [00:00<00:00, 23.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pQ1PQw_mAtcQ7ecjapUBrkG6CC6lxha6
To: /content/Batdongsan_raw_ver1/Saigon_Royal.csv
100% 73.2k/73.2k [00:00<00:00, 102MB/s]
Downloading...
From: https://drive.google.com/uc?id=1__R1fLV_RXmzI0QaSDiLvSvr4bE9yg9S
To: /content/Batdongsan_raw_ver1/Sky_Lake.csv
100% 63.1k/63.1k [00:00<00:00, 89.9MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1zTOmuC8bqZMbf4z-VkJBEyi1nia-otW_t--_22tw9-Q
From (redirected): https://docs.google.com/spreadsheets/d/1zTOmuC8bqZMbf4z-VkJBEyi1nia-otW_t--_22tw9-Q/export?format=xlsx
To: /content/Batdongsan_raw_ver1/Sky_Park
8.29kB [00:00, 3.12MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mjnI_lKaNgYKSP50gKX936RJiEOL8-uB
To: /content/Batdongsan_raw_ver1/Sky_Park.csv
100% 6.28k/6.28k [00:00<00:00, 30.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1T6pk0dUyZOoK6MNOTl2wCDZcTpgsWBzc
To: /content/Batdongsan_raw_ver1/Sunrise_City.csv
100% 154k/154k [00:00<00:00, 99.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1KLuuY8Lv0JFwx8xkLlSebVONCKNTMk4T
To: /content/Batdongsan_raw_ver1/Sunrise_Cityview.csv
100% 28.4k/28.4k [00:00<00:00, 91.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1B6XfIxkJ59RMWFqoW4JUbMcy80hna6vl
To: /content/Batdongsan_raw_ver1/Symphony.csv
100% 32.5k/32.5k [00:00<00:00, 100MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GA0tAb4Iy3Qv0DPstKJ_9L6S1_lpJ_nO
To: /content/Batdongsan_raw_ver1/The_Botanica.csv
100% 63.9k/63.9k [00:00<00:00, 74.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DhFs5PJa9Gba6LK_3kUV2IGT5vQdimiy
To: /content/Batdongsan_raw_ver1/The_EverRich_Infinity.csv
100% 62.6k/62.6k [00:00<00:00, 60.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1YpsK2498txjrxiDmrvjETPUmHIPT6CEh
To: /content/Batdongsan_raw_ver1/The_Grand_Manhattan.csv
100% 62.7k/62.7k [00:00<00:00, 119MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xWZqASgNEzMt0C0zTJlaGmEPZ64kZE9T
To: /content/Batdongsan_raw_ver1/The_Prince_Residence.csv
100% 43.0k/43.0k [00:00<00:00, 105MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NL0Ngg9paY4j747Hfj6tVnDcF5lR0wou
To: /content/Batdongsan_raw_ver1/The_Tresor.csv
100% 84.9k/84.9k [00:00<00:00, 114MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RygfUZqfT8MANUHL7qmLoEVCBJTrjywJ
To: /content/Batdongsan_raw_ver1/Times_City.csv
100% 180k/180k [00:00<00:00, 131MB/s]
Downloading...
From: https://drive.google.com/uc?id=182Gl4Xsrm-ebRVUj8jwcdTUtrEkmTcrd
To: /content/Batdongsan_raw_ver1/Vinhomes_Bắc_Ninh.csv
100% 4.99k/4.99k [00:00<00:00, 12.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1djqPdaTHYwTmjlsBRFfwe0bSQ-_ZWSYT
To: /content/Batdongsan_raw_ver1/Vinhomes_Centralpark.csv
100% 227k/227k [00:00<00:00, 53.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=103dmVHExuf2PRQV0zTiGiGKvQG91EEq6
To: /content/Batdongsan_raw_ver1/Vinhomes_DongKhoi.csv
100% 13.0k/13.0k [00:00<00:00, 58.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1bxJIBcGmziAEC5TX5WNcERh-505Qx7Aq
To: /content/Batdongsan_raw_ver1/vinhomes_gardenia.csv
100% 78.6k/78.6k [00:00<00:00, 130MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1XkSeoa0MfVBzIO0guNq5hTY8_NI72qFSMTi8p9lwEmc
From (redirected): https://docs.google.com/spreadsheets/d/1XkSeoa0MfVBzIO0guNq5hTY8_NI72qFSMTi8p9lwEmc/export?format=xlsx
To: /content/Batdongsan_raw_ver1/Vinhomes_Golden_River_Bason
59.8kB [00:00, 3.17MB/s]
Downloading...
From: https://drive.google.com/uc?id=10NdPGiFw8QXIjXMCrLQDdKWgGK54KGLL
To: /content/Batdongsan_raw_ver1/Vinhomes_Golden_River_Bason.csv
100% 209k/209k [00:00<00:00, 74.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SAn1Pq1_RD_vGJ7zk2YUgNNrMMzlcNo-
To: /content/Batdongsan_raw_ver1/vinhomes_greenparadise.csv
100% 60.0k/60.0k [00:00<00:00, 72.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=19xg2Td3HVzx0oCEgaso98UzlOPhKw1iH
To: /content/Batdongsan_raw_ver1/Vinhomes_Metropolis.csv
100% 71.2k/71.2k [00:00<00:00, 101MB/s]
Downloading...
From: https://drive.google.com/uc?id=12j7qSCoa4jCTy7rMkpb3iMya2hU6T-79
To: /content/Batdongsan_raw_ver1/vinhomes_nct.csv
100% 30.1k/30.1k [00:00<00:00, 70.2MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1vJH583MyrXHb5S7Wi_htIK_zGmEVV9SwUg1ETwpdo8k
From (redirected): https://docs.google.com/spreadsheets/d/1vJH583MyrXHb5S7Wi_htIK_zGmEVV9SwUg1ETwpdo8k/export?format=xlsx
To: /content/Batdongsan_raw_ver1/Vinhomes_Ocean_Park
298kB [00:00, 25.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1lWbiN_NLE91eh5MfRgFIKSMeMN7LhyH9
To: /content/Batdongsan_raw_ver1/Vinhomes_Ocean_Park.csv
100% 916k/916k [00:00<00:00, 160MB/s]
Downloading...
From: https://drive.google.com/uc?id=14-QfA2FU3M6gS13XT25TO3CSH8Lds-9G
To: /content/Batdongsan_raw_ver1/vinhomes_smartcity.csv
100% 587k/587k [00:00<00:00, 139MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1aCv4wML2dDcD8z7Q9inBrR8C8q2aJcn2yNNkpUGZ51M
From (redirected): https://docs.google.com/spreadsheets/d/1aCv4wML2dDcD8z7Q9inBrR8C8q2aJcn2yNNkpUGZ51M/export?format=xlsx
To: /content/Batdongsan_raw_ver1/Vinhomes_Star_City
39.1kB [00:00, 7.80MB/s]
Downloading...
From: https://drive.google.com/uc?id=1CmFMj_Ql0Z6BnQP1dmeMTtuR-0d4rChn
To: /content/Batdongsan_raw_ver1/Vinhomes_Star_City.csv
100% 98.0k/98.0k [00:00<00:00, 83.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1VGRjW1CgWKVJ6dkV3WsoTwBC_DYwA99m
To: /content/Batdongsan_raw_ver1/Vinhomes_West_Point.csv
100% 43.2k/43.2k [00:00<00:00, 42.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vxMnIsqf3ytBTCJjoFdBoCbEABarHeZt
To: /content/Batdongsan_raw_ver1/Wilton_Tower.csv
100% 20.6k/20.6k [00:00<00:00, 76.0MB/s]
Download completed

In [ ]:
import os
os.listdir()

['.config', 'Batdongsan_raw_ver1', 'sample_data']

In [ ]:
import pandas as pd

schema_df = pd.read_csv("Batdongsan_raw_ver1/DMA_Schema - Down.csv")

schema_df.head()

,project_name,brand,location,admin_area,land_area_ha,num_towers,total_apartment,construction_density,dist_cbd_km,dist_metro_km,...,dist_highway_km,dist_airport_km,has_mall,has_school,has_hospital,has_park,has_pool,launch_year,handover_year,ownership
0,Vinhomes Grand Park,Vinhomes,HCM,"Long Thạnh Mỹ, Long Bình","271,8",71.0,44000,"22,53",23,"9,1",...,7,24,1,1,1,1,1,2019,2020.0,Sở hữu lâu dài
1,Vinhomes Ocean Park,Vinhomes,HN,Gia Lâm,423,66.0,50000,19,16,16,...,"0,1",6,1,1,1,1,1,2018,2019.0,Sổ đỏ không thời hạn
2,Vinhomes Golden River Bason,Vinhomes,HCM,Bến Nghé,"25,3",5.0,2680,"18,6","2,6",1,...,27,"9,1",0,1,0,1,1,2016,2018.0,Sở hữu không thời hạn
3,Vinhomes Smartcity,Vinhomes,HN,Nam Từ Liêm,280,49.0,38000,"14,7",14,14,...,"0,5",30,1,1,1,1,1,2018,2020.0,Sở hữu lâu dài
4,Vinhomes Centralpark,Vinhomes,HCM,Thạnh Mỹ Tây,"43,9",18.0,10000,16,"4,8","0,7",...,20,"9,1",1,1,1,1,1,2014,2018.0,Sở hữu lâu dài

In [ ]:
schema_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   project_name          44 non-null     object
 1   brand                 44 non-null     object
 2   location              44 non-null     object
 3   admin_area            44 non-null     object
 4   land_area_ha          44 non-null     object
 5   num_towers            43 non-null     float64
 6   total_apartment       44 non-null     int64
 7   construction_density  44 non-null     object
 8   dist_cbd_km           44 non-null     object
 9   dist_metro_km         40 non-null     object
 10  Metro_city            44 non-null     int64
 11  dist_river_lake_km    44 non-null     object
 12  dist_highway_km       44 non-null     object
 13  dist_airport_km       44 non-null     object
 14  has_mall              44 non-null     int64
 15  has_school            44 non-null     int64
 16  has_hospital          44 non-null     int64
 17  has_park              44 non-null     int64
 18  has_pool              44 non-null     int64
 19  launch_year           44 non-null     int64
 20  handover_year         43 non-null     float64
 21  ownership             44 non-null     object
dtypes: float64(2), int64(8), object(12)
memory usage: 7.7+ KB

In [ ]:
schema_df = schema_df.replace(",", ".", regex=True)

In [ ]:
cols = [
"land_area_ha",
"construction_density",
"dist_cbd_km",
"dist_metro_km",
"dist_river_lake_km",
"dist_highway_km",
"dist_airport_km"
]

for c in cols:
    schema_df[c] = pd.to_numeric(schema_df[c], errors="coerce")

In [ ]:
schema_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   project_name          44 non-null     object
 1   brand                 44 non-null     object
 2   location              44 non-null     object
 3   admin_area            44 non-null     object
 4   land_area_ha          44 non-null     float64
 5   num_towers            43 non-null     float64
 6   total_apartment       44 non-null     int64
 7   construction_density  44 non-null     float64
 8   dist_cbd_km           44 non-null     float64
 9   dist_metro_km         40 non-null     float64
 10  Metro_city            44 non-null     int64
 11  dist_river_lake_km    44 non-null     float64
 12  dist_highway_km       44 non-null     float64
 13  dist_airport_km       44 non-null     float64
 14  has_mall              44 non-null     int64
 15  has_school            44 non-null     int64
 16  has_hospital          44 non-null     int64
 17  has_park              44 non-null     int64
 18  has_pool              44 non-null     int64
 19  launch_year           44 non-null     int64
 20  handover_year         43 non-null     float64
 21  ownership             44 non-null     object
dtypes: float64(9), int64(8), object(5)
memory usage: 7.7+ KB

In [ ]:
import pandas as pd
import os

folder = "Batdongsan_raw_ver1"

dfs = []

for file in os.listdir(folder):
    if file.endswith(".csv") and "schema" not in file.lower():
        path = os.path.join(folder, file)
        df = pd.read_csv(path)
        dfs.append(df)

listing_df = pd.concat(dfs, ignore_index=True)

listing_df.head()

,brand,project,city,url,title,price_vnd,area_m2,price_per_m2,bedrooms,bathrooms,direction,balcony_direction,furnishing,legal_status,posted_date,expired_date,description,listing_type
0,Vinhomes,Vinhomes Royal City,Ha Noi,https://batdongsan.com.vn/ban-can-ho-chung-cu-...,Tổng hợp quỹ căn hộ Royal City cập nhật giá mớ...,1.400000e+10,131.0,106870229.0,3.0,2.0,Đông - Nam,NaN,Đầy đủ,Sổ đỏ/ Sổ hồng,13/03/2026,20/03/2026,Tổng hợp quỹ căn hộ Royal City giá cập nhật mớ...,vip-gold
1,Vinhomes,Vinhomes Royal City,Ha Noi,https://batdongsan.com.vn/ban-can-ho-chung-cu-...,Chính chủ bán gấp căn hộ 3 ngủ R4 căn đẹp view...,1.430000e+10,105.0,136190476.0,3.0,2.0,Tây - Nam,Đông - Bắc,Cơ bản,Sổ đỏ/ Sổ hồng,12/03/2026,19/03/2026,"Chính chủ cần bán gấp căn hộ 3PN, 2 WC, 105m² ...",vip-gold
2,Vinhomes,Vinhomes Royal City,Ha Noi,https://batdongsan.com.vn/ban-can-ho-chung-cu-...,"Tổng hợp quỹ căn hộ 1PN, 2PN, 3PN, 4PN, duplex...",NaN,133.0,NaN,NaN,NaN,NaN,NaN,NaN,Sổ đỏ/ Sổ hồng,27/02/2026,14/03/2026,Ra mắt quỹ căn hộ chủ nhà gửi bán mới nhất tại...,vip-gold
3,Vinhomes,Vinhomes Royal City,Ha Noi,https://batdongsan.com.vn/ban-can-ho-chung-cu-...,Duy nhất tại Royal City bán cặp đập thông VIP ...,5.500000e+10,350.0,157142857.0,6.0,4.0,Đông - Bắc,Đông - Nam,Full nội thất xịn xò.,Sổ đỏ/ Sổ hồng,11/03/2026,18/03/2026,Cần bán căn hộ đẹp nhất Royal City.+ Diện tích...,vip-silver
4,Vinhomes,Vinhomes Royal City,Ha Noi,https://batdongsan.com.vn/ban-can-ho-chung-cu-...,"ĐA DẠNG CĂN HỘ ROYAL CITY, PHÙ HỢP MỌI PHÂN KH...",1.280000e+10,110.0,116363636.0,3.0,2.0,Tây - Bắc,Nam,Đầy đủ,Sổ đỏ/ Sổ hồng,09/03/2026,16/03/2026,ẬP NHẬT QUỸ CĂN HỘ BÁN HOT NHẤT ROYAL CITY THÁ...,vip-silver

In [ ]:
listing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4882 entries, 0 to 4881
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              4882 non-null   object
 1   project            4882 non-null   object
 2   city               4882 non-null   object
 3   url                4882 non-null   object
 4   title              4882 non-null   object
 5   price_vnd          4537 non-null   float64
 6   area_m2            4882 non-null   float64
 7   price_per_m2       4537 non-null   float64
 8   bedrooms           4583 non-null   float64
 9   bathrooms          4393 non-null   float64
 10  direction          2069 non-null   object
 11  balcony_direction  2274 non-null   object
 12  furnishing         3837 non-null   object
 13  legal_status       4024 non-null   object
 14  posted_date        4882 non-null   object
 15  expired_date       4882 non-null   object
 16  description        4882 non-null   object
 17  listing_type       4882 non-null   object
dtypes: float64(5), object(13)
memory usage: 686.7+ KB

In [ ]:
set(listing_df["project"]) - set(schema_df["project_name"])

{'River_Gate',
 'Sunrise City',
 'The Everrich I',
 'Vinhomes GrandPark',
 'Vinhomes Royal City ',
 'Vinhomes Sky Park '}

In [ ]:
listing_df["project"] = (
    listing_df["project"]
    .str.lower()
    .str.strip()
    .str.replace("_", " ")
)

In [ ]:
listing_df["project"] = listing_df["project"].replace({
    "vinhomes grandpark": "vinhomes grand park",
    "the everrich i": "the everrich 1",
    "river gate": "rivergate"
})

In [ ]:
schema_df["project_name"] = (
    schema_df["project_name"]
    .str.lower()
    .str.strip()
)

In [ ]:
set(listing_df["project"]) - set(schema_df["project_name"])

set()

In [ ]:
listing_df["brand"] = listing_df["brand"].str.strip().str.title()
schema_df["brand"] = schema_df["brand"].str.strip().str.title()

In [ ]:
listing_df["city"] = listing_df["city"].str.strip().str.title()
schema_df["location"] = schema_df["location"].str.strip().str.title()

In [ ]:
city_map = {
    "Hcm": "Ho Chi Minh City",
    "Tp.Hcm": "Ho Chi Minh City",
    "Ho Chi Minh": "Ho Chi Minh City",
    "Hồ Chí Minh": "Ho Chi Minh City",

    "Hn": "Hanoi",
    "Ha Noi": "Hanoi",
    "Hà Nội": "Hanoi"
}

In [ ]:
listing_df["city"] = listing_df["city"].replace(city_map)
schema_df["location"] = schema_df["location"].replace(city_map)

In [ ]:
merged_df = listing_df.merge(
    schema_df,
    left_on="project",
    right_on="project_name",
    how="left"
)

In [ ]:
merged_df = merged_df.drop(columns=["project_name"])

In [ ]:
merged_df.isna().sum().sort_values(ascending=False)

direction               2813
balcony_direction       2608
furnishing              1045
legal_status             858
bathrooms                489
price_per_m2             345
price_vnd                345
bedrooms                 299
dist_metro_km            134
handover_year             44
num_towers                35
brand_x                    0
project                    0
url                        0
city                       0
area_m2                    0
title                      0
posted_date                0
expired_date               0
brand_y                    0
location                   0
listing_type               0
description                0
land_area_ha               0
admin_area                 0
construction_density       0
total_apartment            0
Metro_city                 0
dist_river_lake_km         0
dist_highway_km            0
dist_cbd_km                0
dist_airport_km            0
has_mall                   0
has_hospital               0
has_school                 0
has_park                   0
has_pool                   0
launch_year                0
ownership                  0
dtype: int64

In [ ]:
merged_df["brand_x"].isna().sum()

np.int64(0)

In [ ]:
(merged_df["brand_x"] != merged_df["brand_y"]).sum()

np.int64(0)

In [ ]:
merged_df[merged_df["brand_x"] != merged_df["brand_y"]][
    ["project","brand_x","brand_y"]
].head(20)

Empty DataFrame
Columns: [project, brand_x, brand_y]
Index: []

In [ ]:
merged_df.columns

Index(['brand_x', 'project', 'city', 'url', 'title', 'price_vnd', 'area_m2',
       'price_per_m2', 'bedrooms', 'bathrooms', 'direction',
       'balcony_direction', 'furnishing', 'legal_status', 'posted_date',
       'expired_date', 'description', 'listing_type', 'brand_y', 'location',
       'admin_area', 'land_area_ha', 'num_towers', 'total_apartment',
       'construction_density', 'dist_cbd_km', 'dist_metro_km', 'Metro_city',
       'dist_river_lake_km', 'dist_highway_km', 'dist_airport_km', 'has_mall',
       'has_school', 'has_hospital', 'has_park', 'has_pool', 'launch_year',
       'handover_year', 'ownership'],
      dtype='object')

In [ ]:
merged_df.isna().sum().sort_values(ascending=False)

direction               2813
balcony_direction       2608
furnishing              1045
legal_status             858
bathrooms                489
price_per_m2             345
price_vnd                345
bedrooms                 299
dist_metro_km            134
handover_year             44
num_towers                35
brand_x                    0
project                    0
url                        0
city                       0
area_m2                    0
title                      0
posted_date                0
expired_date               0
brand_y                    0
location                   0
listing_type               0
description                0
land_area_ha               0
admin_area                 0
construction_density       0
total_apartment            0
Metro_city                 0
dist_river_lake_km         0
dist_highway_km            0
dist_cbd_km                0
dist_airport_km            0
has_mall                   0
has_hospital               0
has_school                 0
has_park                   0
has_pool                   0
launch_year                0
ownership                  0
dtype: int64

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4882 entries, 0 to 4881
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand_x               4882 non-null   object
 1   project               4882 non-null   object
 2   city                  4882 non-null   object
 3   url                   4882 non-null   object
 4   title                 4882 non-null   object
 5   price_vnd             4537 non-null   float64
 6   area_m2               4882 non-null   float64
 7   price_per_m2          4537 non-null   float64
 8   bedrooms              4583 non-null   float64
 9   bathrooms             4393 non-null   float64
 10  direction             2069 non-null   object
 11  balcony_direction     2274 non-null   object
 12  furnishing            3837 non-null   object
 13  legal_status          4024 non-null   object
 14  posted_date           4882 non-null   object
 15  expired_date          4882 non-null   object
 16  description           4882 non-null   object
 17  listing_type          4882 non-null   object
 18  brand_y               4882 non-null   object
 19  location              4882 non-null   object
 20  admin_area            4882 non-null   object
 21  land_area_ha          4882 non-null   float64
 22  num_towers            4847 non-null   float64
 23  total_apartment       4882 non-null   int64
 24  construction_density  4882 non-null   float64
 25  dist_cbd_km           4882 non-null   float64
 26  dist_metro_km         4748 non-null   float64
 27  Metro_city            4882 non-null   int64
 28  dist_river_lake_km    4882 non-null   float64
 29  dist_highway_km       4882 non-null   float64
 30  dist_airport_km       4882 non-null   float64
 31  has_mall              4882 non-null   int64
 32  has_school            4882 non-null   int64
 33  has_hospital          4882 non-null   int64
 34  has_park              4882 non-null   int64
 35  has_pool              4882 non-null   int64
 36  launch_year           4882 non-null   int64
 37  handover_year         4838 non-null   float64
 38  ownership             4882 non-null   object
dtypes: float64(14), int64(8), object(17)
memory usage: 1.5+ MB

In [ ]:
merged_df.duplicated(subset=["title","area_m2","price_vnd"]).sum()

np.int64(134)

In [ ]:
merged_df = merged_df.drop_duplicates(
    subset=["title","area_m2","price_vnd"]
)

In [ ]:
merged_df = merged_df.dropna(subset=["price_vnd","price_per_m2"])

In [ ]:
merged_df.isna().sum().sort_values(ascending=False)

direction               2530
balcony_direction       2352
furnishing               936
legal_status             750
bathrooms                421
bedrooms                 257
dist_metro_km             76
handover_year             42
num_towers                20
title                      0
price_vnd                  0
city                       0
project                    0
brand_x                    0
url                        0
area_m2                    0
expired_date               0
posted_date                0
description                0
brand_y                    0
location                   0
listing_type               0
price_per_m2               0
land_area_ha               0
admin_area                 0
construction_density       0
total_apartment            0
Metro_city                 0
dist_river_lake_km         0
dist_highway_km            0
dist_cbd_km                0
dist_airport_km            0
has_mall                   0
has_hospital               0
has_school                 0
has_park                   0
has_pool                   0
launch_year                0
ownership                  0
dtype: int64

In [ ]:
merged_df.shape

(4409, 39)

In [ ]:
merged_df = merged_df.drop(columns=["brand_y"])

In [ ]:
merged_df = merged_df.rename(columns={"brand_x": "brand"})

In [ ]:
merged_df['posted_date'] = pd.to_datetime(
    merged_df['posted_date'],
    dayfirst=True,
    errors='coerce'
)

In [ ]:
merged_df['expired_date'] = pd.to_datetime(
    merged_df['expired_date'],
    dayfirst=True,
    errors='coerce'
)

In [ ]:
merged_df[['posted_date','expired_date']].dtypes

posted_date     datetime64[ns]
expired_date    datetime64[ns]
dtype: object

In [ ]:
merged_df = merged_df.drop(columns=["location"])

In [ ]:
merged_df.to_csv("Batdongsan_merge_ver1.csv", index=False)

In [ ]:
cat_cols = [
    "direction",
    "balcony_direction",
    "furnishing",
    "legal_status",
    "listing_type",
    "ownership"
]

In [ ]:
merged_df.columns

Index(['brand', 'project', 'city', 'url', 'title', 'price_vnd', 'area_m2',
       'price_per_m2', 'bedrooms', 'bathrooms', 'direction',
       'balcony_direction', 'furnishing', 'legal_status', 'posted_date',
       'expired_date', 'description', 'listing_type', 'admin_area',
       'land_area_ha', 'num_towers', 'total_apartment', 'construction_density',
       'dist_cbd_km', 'dist_metro_km', 'Metro_city', 'dist_river_lake_km',
       'dist_highway_km', 'dist_airport_km', 'has_mall', 'has_school',
       'has_hospital', 'has_park', 'has_pool', 'launch_year', 'handover_year',
       'ownership'],
      dtype='object')

In [ ]:
for col in cat_cols:
    merged_df[col] = (
        merged_df[col]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

In [ ]:
for col in cat_cols:
    print("\n====================")
    print("COLUMN:", col)
    print(merged_df[col].value_counts(dropna=False))

====================
COLUMN: direction
direction
nan           2530
Đông - Nam     460
Đông - Bắc     410
Tây - Bắc      362
Tây - Nam      286
Đông           108
Bắc             96
Nam             90
Tây             67
Name: count, dtype: int64

====================
COLUMN: balcony_direction
balcony_direction
nan           2352
Đông - Nam     673
Đông - Bắc     397
Tây - Nam      362
Tây - Bắc      306
Nam            127
Đông            98
Bắc             60
Tây             34
Name: count, dtype: int64

====================
COLUMN: furnishing
furnishing
Đầy đủ                                                                                  1776
nan                                                                                      936
Cơ bản                                                                                   903
Đầy đủ.                                                                                  121
Không nội thất                                                                            84
                                                                                        ...
Nội thất đầy đủ xịn                                                                        1
Nội thất dính tường, layout như căn hộ trong hình                                          1
Nhà full NT cao cấp                                                                        1
Nhà full NT cao cấp.                                                                       1
Điều hòa âm trần, sàn gỗ, toàn bộ bếp tủ bếp, các thiết vị điện và thiết bị vệ sinh.       1
Name: count, Length: 299, dtype: int64

====================
COLUMN: legal_status
legal_status
Sổ đỏ/ Sổ hồng                          2063
Hợp đồng mua bán                        1172
nan                                      750
Đang chờ sổ                              103
Sổ đỏ/ Sổ hồng.                           66
                                        ...
Văn bản thoã thuận                         1
Văn Bản Thỏa thuận, ký HDMB T3/2026        1
Văn Bản Thỏa Thuận (ký HĐMB T3/2026)       1
Văn bản thỏa thuận                         1
Văn Bản Thoả Thuận                         1
Name: count, Length: 68, dtype: int64

====================
COLUMN: listing_type
listing_type
vip-normal     4052
vip-silver      186
vip-gold         88
vip-diamond      83
Name: count, dtype: int64

====================
COLUMN: ownership
ownership
Sở hữu lâu dài                                                                                   2766
Sổ đỏ không thời hạn                                                                              728
Sở hữu không thời hạn                                                                             253
Sổ đỏ lâu dài                                                                                     207
Sổ hồng lâu dài                                                                                   194
Chưa cấp sổ                                                                                       184
Chưa cấp sổ đồng loạt                                                                              39
Sở hữu lâu dài đối với khách hàng người Việt Nam. 50 năm đối với khách hàng người nước ngoài.      20
Sổ hồng                                                                                            18
Name: count, dtype: int64

In [ ]:
for col in cat_cols:
    print("\n", col)
    print(sorted(merged_df[col].dropna().unique()))

 direction
['Bắc', 'Nam', 'Tây', 'Tây - Bắc', 'Tây - Nam', 'nan', 'Đông', 'Đông - Bắc', 'Đông - Nam']

 balcony_direction
['Bắc', 'Nam', 'Tây', 'Tây - Bắc', 'Tây - Nam', 'nan', 'Đông', 'Đông - Bắc', 'Đông - Nam']

 furnishing
['+ Nội thất hoàn thiện cao cấp với vật liệu kính, gỗ, đá. + Trang bị điều hòa, tủ lạnh, giường...', '+ Nội thất đầy đủ: Điều hòa, giường, tủ lạnh.', '+ Đầy đủ nội thất cao cấp.', '- *Nội thất: Đầy đủ, cao cấp, được trang bị tiện nghi hiện đại và sang trọng.', '- Ban giao hoàn thiện theo tiêu chuẩn từ chủ đầu (điển hình như Smarthomes Vsmart, máy lạnh âm trần, gỗ xương cá trong phòng ngủ, gạch men 80x80cm... ).', '- Có đầy đủ nội thất chỉ cần vào ở.', '- Có đầy đủ nội thất.', '- Full nội thất cao cấp.', '- Full nội thất như ảnh.', '- Full nội thất.', '- Nhà full NT đẹp.', '- Nội thất căn hộ theo phong cách Châu Âu.', '- Nội thất cơ bản: Bếp, rèm.', '- Nội thất thiết kế chủ nhà để lại toàn bộ nội thất.', '- Nội thất đầy đủ, bao gồm điều hòa, giường, tủ lạnh...', '- Nội thất: Full đẹp như hình.', '- Tặng khách mua đầy đủ nội thất cực đẹp.', '- Để lại nội thất cho khách thiện chí.', 'Bàn giao cao cấp: Điều hoà âm trần, tủ bếp, tủ quần áo, sàn xương cá.', 'Bàn giao chuẩn cao cấp quốc tế theo chủ đầu tư.', 'Bàn giao cơ bản tường, trần, sàn, thiết bị vệ sinh, 3 máy lạnh, hệ thống Smart Homes thông minh.', 'Bàn giao cơ bản tường, trần, sàn, thiết bị vệ sinh, 3 máy lạnh.', 'Bàn giao cơ bản tường, trần, sàn, thiết bị vệ sinh, 4 máy lạnh.', 'Bàn giao cơ bản.', 'Bàn giao full nội thất liền tường cao cấp.', 'Bàn giao full nội thất liền tường, full sàn gỗ, điều hòa, tủ bếp, thiết bị vệ sinh.', 'Bàn giao full nội thất mới 98% do ít ở đang ở nhà mặt đất.', 'Bàn giao full nội thất, tivi, tủ lạnh, sofa, bếp, rèm điều hòa, giường,...', 'Bàn giao full nội thất.', 'Bàn giao full thiết bị liền tường cao cấp.', 'Bàn giao full thiết bị liền tường, như điều hòa, tủ bếp, bếp từ, chậu rửa, khóa vân tay, sàn gỗ, trần thạch cao...', 'Bàn giao full thiết bị liền tường.', 'Bàn giao hoàn thiện', 'Bàn giao hoàn thiện cơ bản tiêu chuẩn chủ đầu tư.', 'Bàn giao hoàn thiện với các thiết bị vệ sinh nhập khẩu từ Châu Âu, máy lạnh âm trần + hệ thống smarthome.', 'Bàn giao lại full nội thất hàng nhập khẩu nội địa Nhật, đã làm thêm sàn gỗ phòng khách tổng gần 400tr tiền nội thất, thiết kế thông minh.', 'Bàn giao nguyên bản CĐT: Sàn gỗ, điều hòa âm trần, tủ bếp, thiết bị vệ sinh, hệ thống smart home. View thoáng, nhà sáng.', 'Bàn giao nội thất cao cấp An Cường, bếp, tủ quần áo, máy lạnh âm trần, máy nước nóng lạnh..', 'Bàn giao nội thất cao cấp: Smart - home, Hafele, Toto, LG.', 'Bàn giao nội thất chủ đầu tư.', 'Bàn giao nội thất cơ bản, lầu thấp.', 'Bàn giao nội thất full gỗ liền tường.', 'Bàn giao nội thất hoàn thiện Bếp An Cường, tủ áo quần, thiết bị vệ sinh, điều hòa âm trần, hệ thống smart home.', 'Bàn giao nội thất liền.', 'Bàn giao theo tiêu chuẩn cơ bản, bao gồm: Trần thạch cao; full sàn gỗ; Bếp và hệ tủ bếp theo tiêu chuẩn thiết bị cao cấp như: Hafele, Electrolux, Malloca....', 'Bàn giao theo tiêu chuẩn của CĐT', 'Bàn giao theo tiêu chuẩn của CĐT.', 'Bán kèm nội thất', 'Bán tặng lại toàn bộ nội thất.', 'Bếp - rèm', 'Bếp Hafele, thiết bị vệ sinh Kohler.', 'Bếp, Rèm', 'Bếp, rèm, máy nóng lạnh.', 'Bếp, rèm.', 'Cao cấp', 'Cao cấp hiện đại', 'Cao cấp, đầy đủ.', 'Cao cấp.', 'Chất lượng bàn giao nội thất cao cấp thương hiệu nổi tiếng.', 'Chủ Đầu Tư', 'Chủ đầu tư', 'Chủ đầu tư liền tường', 'Chủ đầu tư.', 'Có bếp rèm.', 'Có hệ Thống bếp cao cấp - full vệ sinh, mát lạnh.', 'Có máy lạnh, rèm cửa', 'Có máy lạnh, rèm cửa.', 'Có máy lạnh, tủ bếp trên, tủ bếp dưới, bếp từ (loại 3 bếp), máy hút mùi, ló nướng, bồn rửa chén. WC có bồn cầu, lavabo, máy nước nóng. WC phòng ngủ master có bồn cầu thông minh.', 'Có nội thất', 'Có nội thất.', 'Có sẵn nội thất liền tường (tủ bếp, điều hòa, nóng lạnh). Có sẵn nội thất liền tường (tủ bếp, điều hòa, nóng lạnh).', 'Có sẵn nội thất.', 'Có thể lựa chọn mua không nội thất hoặc đầy đủ nội thất.', 'Căn hộ trang bị đầy đủ nội thất đẹp như: Tivi, tủ lạnh, máy giặt, sofa, bàn trà, giường tủ...', 'Căn hộ được thiết kế và làm nội thất cao cấp, ốp gỗ full tường.', 'Căn hộ được trang bị nội thất đầy đủ: Sàn gỗ, điều hòa các phòng, tivi, sofa, giường, tủ đồ, bàn ăn nhà bếp, thiết bị nhà bếp đầy đủ, hệ thống rèm cửa tự động, máy giặt...', 'Căn hộ đều đã đầy đủ tủ bếp, điều hòa, nóng lạnh, tủ quần áo, bàn ăn, tivi, sofa da, giường đệm, tủ lạnh. Căn hộ đều đã đầy đủ tủ bếp, điều hòa, nóng lạnh, tủ quần áo, bàn ăn, tivi, sofa da, giường...', 'CĐT hỗ trợ gói NT (theo DS căn) + voucher NT 1%', 'Cơ bản', 'Cơ bản - Nội thất: Căn hộ tiêu chuẩn Ruby. Đầy đủ các nội thất liền tường: Điều hòa âm trần, tủ bếp, bếp ga, hút mùi. Sàn gỗ, tủ âm tường phòng ngủ. Khách hàng khi mua sử dụng chỉ cần mua thêm.', 'Cơ bản chủ đầu tư nhà mới 100%.', 'Cơ bản.', 'Cơ bản: Với các thiết bị cao cấp bậc nhất đến từ Bếp Hafele, Thiết bị vệ sinh Kohler.', 'Cơ bản: Điều hoà âm, hệ thống nóng lạnh, sàn gỗ, khoá từ.', 'Full', 'Full NT', 'Full NT sang xịn mịn', 'Full NT theo concept Nhật', 'Full NT xịn sò', 'Full NT, đầy đủ công năng, dọn vào ở ngay', 'Full NT, đầy đủ công năng, không phải NT lắp ghép', 'Full NT.', 'Full cao cấp', 'Full cao cấp.', 'Full gỗ.', 'Full nội thất', 'Full nội thất cao cấp', 'Full nội thất cao cấp mới làm - nhà như ảnh.', 'Full nội thất cao cấp như hình chỉ việc xách vali vào ở.', 'Full nội thất cao cấp, khách mua chỉ việc xách vali về ở.', 'Full nội thất cao cấp.', 'Full nội thất gỗ', 'Full nội thất gỗ cao cấp.', 'Full nội thất gỗ đẹp, sang.', 'Full nội thất gỗ.', 'Full nội thất hiện đại, dọn vào ở ngay.', 'Full nội thất hiện đại.', 'Full nội thất hoặc không nội thất.', 'Full nội thất liền tường cao cấp chuẩn Châu Âu, kính LowE 3 lớp, điều hòa âm trần...', 'Full nội thất liền tường cao cấp, thiết bị vệ sinh, thiết bị bếp, kính LowE 3 lớp, điều hòa Multi âm trần', 'Full nội thất liền tường cao cấp.', 'Full nội thất liền tường cao cấp. - Tủ bếp trên dưới. - Bếp từ 3 vùng nấu, máy hút mùi. - Tủ âm phòng ngủ. - Thiết bị thương hiệu Hafele, Dessmann.', 'Full nội thất mới đẹp như hình.', 'Full nội thất như hình', 'Full nội thất như ảnh.', 'Full nội thất xịn sò.', 'Full nội thất xịn xò.', 'Full nội thất đầy đủ như hình', 'Full nội thất đầy đủ, bao gồm điều hòa, giường, tủ lạnh...', 'Full nội thất đẹp.', 'Full nội thất, đồ điện tử.', 'Full nội thất.', 'Full thiết bị vệ sinh cao cấp, giường, tủ, bếp, điều hòa, nóng lạnh, ghế sofa, kệ tivi...', 'Full tủ bếp trên và dưới, lò nướng, máy hút mùi, bếp nấu, bồn rửa chén - Tất cả đều hàng nhập khẩu từ thương hiệu Hafele, Kohler. - Full thiết bị vệ sinh bồn cầu thông minh tự động, máy nóng lạnh.', 'Full đồ cao cấp.', 'Full đồ mới tinh 100%, full đồ điện tử tivi, tủ lạnh Side By Side Door In Door, máy giặt, máy sấy đập hộp chưa bóc tem thế hệ mới nhất của LG.', 'Full đồ như hình chỉ việc xách vali về ở.', 'Full đồ như ảnh mới 100%, chỉ việc dọn vào ở', 'Full đồ nội thất và đồ điện tử.', 'Full đồ nội thất: Thiết bị bếp, tủ quần áo âm tường, thiết bị vệ sinh, điều hoà âm trần. Ngoài ra đã thiết kế thêm sofa, bàn ăn, giường, đồ điện tử.', 'Full đồ đẹp.', 'Full đồ đủ.', 'Full đồ.', 'Full.', 'Gói hỗ trợ hoàn thiện cho thuê 10% + gói tặng quà NT lên đến 300tr', 'Gói ruby cao cấp', 'Gần full nội thất (Tủ bếp trên dưới, bếp từ, máy hút mùi, máy nước nóng, tủ quần áo,... ).', 'Gần full nội thất.', 'Hoàn thiện cơ bản', 'Hoàn thiện full nội thất cao cấp, với thiết bị ngoại nhập, bao gồm cả TV, tủ lạnh Side By Side 55L, thiết bị nhà bếp,...', 'Hoàn thiện full nội thất đẹp.', 'Hoàn thiện nội thất theo tiêu chuẩn chủ đầu tư.', 'Hệ thống tủ bếp + bếp, 3 điều hòa, tivi, tủ lạnh, máy giặt, máy sấy, sofa, bàn trà.', 'Hệ tủ bếp, thiết bị nhà vệ sinh, lát gạch phòng khách - gỗ phòng ngủ.', 'Không nội thất', 'Không nội thất.', 'Ko đồ.', 'Liền tường cao cấp', 'Máy giặt, máy sấy quần áo, tủ lạnh, điều hòa, bếp từ, lò nướng, giàn phơi, giường tủ.', 'Mới', 'NTCB', 'NTCB.', 'Nguyên bản', 'Nguyên bản Chủ Đầu Tư bàn giao', 'Nguyên bản CĐT', 'Nguyên bản CĐT, nhà mới 100% chưa sử dụng.', 'Nguyên bản CĐT.', 'Nhà full NT cao cấp', 'Nhà full NT cao cấp.', 'Nhà full NT.', 'Nhà mới tinh chưa ở, có đồ nội thất.', 'Nhà nội thất CĐT, nhà mới 100%.', 'Nhà trống, theo tiêu chuẩn bàn giao của CĐT', 'Nhà trống.', 'Nhà tôi đầy đủ nội thất đẹp, làm để ở nên tôi làm chỉn chu, tỉ mỉ.', 'Nhà đã có đầy đủ nội thất.', 'Nhà đã đầy đủ nội thất đẹp.', 'Nhà đầy đủ nội thất còn mới và đẹp.', 'Nhà đầy đủ nội thất.', 'Nhà để lại toàn bộ nội thất về ở ngay được.', 'Nội thất NB CĐT.', 'Nội thất bàn giao CĐT.', 'Nội thất bàn giao cao cấp từ chủ đầu tư Masterise Homes', 'Nội thất bàn giao cơ bản chất lượng chuẩn Vinhomes.', 'Nội thất bàn giao nhập khẩu từ châu Âu.', 'Nội thất bàn giao: Hoàn thiện bếp sang trọng, hệ thống rèm, máy lạnh âm trần cao cấp.', 'Nội thất cao cấp', 'Nội thất cao cấp, chỉ cần mang vali vào ở.', 'Nội thất cao cấp.', 'Nội thất cao cấp. Tivi, bộ ghế sofa, bàn ăn, tủ lạnh, máy lạnh, máy nước nóng, tủ áo âm tường, giường, nệm Kymdan, microwave, bếp hiện đại, cáp, wi - fi internet...', 'Nội thất chủ đầu tư', 'Nội thất có bản.', 'Nội thất cơ bản bếp rèm, tủ lạnh.', 'Nội thất cơ bản chủ đầu tư.', 'Nội thất cơ bản của CĐT', 'Nội thất cơ bản.', 'Nội thất cơ bản: Bếp, rèm.', 'Nội thất do CDT bàn giao: - Bàn ăn + ghế, Sofa + bàn trà, Gường nệm + đầu đường đôn gường, Rèm cửa. - Đồ điện: Tivi - tủ lạnh - hệ thống bếp - lò nướng - bình đun nước - máy lạnh - máy giặt - nồi cơm', 'Nội thất dính tường, layout như căn hộ trong hình', 'Nội thất full đồ.', 'Nội thất full.', 'Nội thất hoàn thiện cao cấp chủ đầu tư.', 'Nội thất hoàn thiện chủ đầu tư.', 'Nội thất hoàn thiện cơ bản', 'Nội thất hoàn thiện cơ bản có máy lạnh, hệ thống điện, thiết bị Vệ sinh cao cấp.', 'Nội thất liền tường, full bếp, tủ quần áo, full thiết bị vệ sinh cao cấp, điều hoà âm trần.', 'Nội thất liền tường: Bếp, điều hòa, thiết bị vệ sinh, hệ thống Smarthome. Ban công kính hiện đại, an toàn. Sàn gỗ bền đẹp, sang trọng.', 'Nội thất làm đẹp.', 'Nội thất mình làm đồ cẩn thận và chỉnh chu.', 'Nội thất mới', 'Nội thất mới 100%.', 'Nội thất mới sắm', 'Nội thất mới, đẹp, hoàn thiện đồng bộ.', 'Nội thất nguyên bản CĐT full liền tường.', 'Nội thất nguyên bản chủ đầu tư hoặc đầy đủ nội thất tùy theo từng căn.', 'Nội thất như hình', 'Nội thất nhập khẩu.', 'Nội thất sang trọng', 'Nội thất siêu cao cấp, nhập khẩu từ ý: Tủ lạnh âm tường, lò nướng...', 'Nội thất tiện nghi, hiện đại.', 'Nội thất văn phòng', 'Nội thất với đầy đủ trang thiết bị, hiện đại cao cấp chuẩn 5 sao. - Hầu hết căn hộ đều có sổ hồng, nội thất với đầy đủ trang thiết bị, hiện đại cao cấp chuẩn 5 sao. Chỉ việc xách vali đến và tận hưởng', 'Nội thất đã hoàn thiện.', 'Nội thất đầy đủ', 'Nội thất đầy đủ CĐT mới 100%.', 'Nội thất đầy đủ với điều hòa, giường, tủ.', 'Nội thất đầy đủ với điều hòa, tủ lạnh, giường ngủ...', 'Nội thất đầy đủ với điều hòa, tủ lạnh, giường...', 'Nội thất đầy đủ xịn', 'Nội thất đầy đủ.', 'Nội thất đầy đủ: Điều hòa, tủ lạnh, giường, bàn ghế...', 'Nội thất đẹp', 'Nội thất đẹp.', 'Nội thất đẹp: Bàn giao như ảnh.', 'Nội thất để lại (máy lạnh, giường, tủ quần áo... ).', 'Nội thất đủ đồ cơ bản + thiết bị điện tử.', 'Nội thất đủ đồ.', 'Nội thất: Bàn giao nguyên bản chủ đầu tư.', 'Nội thất: Cơ bản theo chủ đầu tư.', 'Nội thất: Full nội thất cao cấp và sang trọng.', 'Nội thất: Khách có thể vào ở ngay.', 'Nội thất: Nhà mới, có bếp rèm, tiện vào ở ngay.', 'Nội thất: Đầy đủ nội thất.', 'Sang xịn mịn', 'Sẵn nội thất cơ bản.', 'Thiết bị điện tử cao cấp điều hoà âm trần Daikin, bếp lò nướng máy giặt máy sấy Bosch, phụ kiện Hafele.', 'Tiêu chuẩn bàn giao cao cấp: Full nội thất cơ bản (sàn gỗ, tủ bếp, thiết bị vệ sinh, điều hòa âm trần, kính Low - E... ).', 'Trang bị nội thất đầy đủ hiện đại gỗ An Cường.', 'Trang bị nội thất đầy đủ.', 'Trang bị điều hòa, tủ lạnh, và các nội thất cần thiết khác.', 'Trang bị đầy đủ tiện nghi như điều hòa, tủ lạnh, giường,...', 'Trống.', 'Tặng NT.', 'Tặng full NT cao cấp.', 'Tặng nóng lạnh và điều hòa âm trần', 'Tặng nội thất cơ bản, hệ tủ bếp Hafale, Kohler, Gessi và điều hòa Panasonic.', 'Tặng nội thất full.', 'Tặng nội thất.', 'Tủ bếp, Tủ quần áo, Bếp từ, Máy hút, Hệ thống máy nóng lạnh,..', 'Với các thiết bị cao cấp bậc nhất đến từ Bếp Hafele, Thiết bị vệ sinh Kohler.', 'Với các thiết bị cao cấp bậc nhất đến từ bếp Hafele, thiết bị vệ sinh Kohler.', 'Với các thiết bị cao cấp bậc nhất đến từ bếp Hafele, thiết bị vệ sinh kohler.', 'Với các thiết bị cao cấp bậc nhất đến từ bếp hafele, thiết bị vệ sinh kohler.', 'nan', 'Điều hòa âm trần, sàn gỗ, toàn bộ bếp tủ bếp, các thiết vị điện và thiết bị vệ sinh.', 'Đã hoàn thiện đẹp, cao cấp và sang trọng.', 'Đã lắp đặt 4 điều hòa và 1 bình nóng lạnh, sẵn sàng để sử dụng.', 'Đã trang bị đầy đủ nội thất cao cấp, trang thiết bị nhà vệ sinh sang trọng từ trong ra ngoài.', 'Đã trang bị đầy đủ nội thất cao cấp.', 'Đã đầy đủ nội thất.', 'Đầy đủ', 'Đầy đủ (full).', 'Đầy đủ + Cửa mở 2 cánh, chống cháy quá 60 độ tự mở cửa. + Kính căn hộ chống tia UV và chống nhiệt và thiết kế Full kịch từ sàn lên tới trần rất sang trọng. + Sàn gỗ cao cấp, Điều hòa âm trần. Tủ bếp l', 'Đầy đủ - Bàn giao full nội thất đồ điện tử + điều hòa (LH 0929169691 để nhận thêm thông tin).', 'Đầy đủ - Chủ làm nội thất để ở nên chọn đồ gỗ tốt và thiết bị đắt tiền.', 'Đầy đủ - Nhà đã làm nội thất đẹp gỗ đắt tiền - Tình trạng còn gần như mới.', 'Đầy đủ - Sổ đỏ cầm tay sẵn sàng giao dịch. Căn hộ đã đầy đủ nội thất chỉ việc xách vali về ở.', 'Đầy đủ Bàn giao full nội thất liền tường cao cấp.', 'Đầy đủ Căn hộ đã đầy đủ tủ bếp, điều hòa, nóng lạnh, tủ quần áo, bàn ăn, sofa, giường đệm, tủ lạnh, máy giặt.', 'Đầy đủ Căn hộ đã đầy đủ tủ bếp, điều hòa, nóng lạnh, tủ quần áo, bàn ăn, sofa, giường đệm, tủ lạnh, máy giặt. Căn hộ đã đầy đủ tủ bếp, điều hòa, nóng lạnh, tủ quần áo, bàn ăn, sofa, giường đệm, tủ lạn', 'Đầy đủ Căn đầy đủ nội thất.', 'Đầy đủ Nhà đã sắm đầy đủ nội thất: Tivi tủ lạnh, máy giặt hệ thống tủ bếp đầy đủ, Giường tủ quần áo đồ mới đẹp.', 'Đầy đủ Nội thất bàn giao cao cấp:', 'Đầy đủ nhà đã sắm đầy đủ nội thất: Tivi tủ lạnh, máy giặt hệ thống tủ bếp đầy đủ, giường tủ quần áo đồ mới đẹp.', 'Đầy đủ nội thất', 'Đầy đủ nội thất + điện tử.', 'Đầy đủ nội thất cao cấp.', 'Đầy đủ nội thất liền tường: Bếp, điều hòa, thiết bị vệ sinh, hệ thống Smarthome.', 'Đầy đủ nội thất mới, đẹp, sang trọng.', 'Đầy đủ nội thất như điều hòa, tủ lạnh, giường ngủ.', 'Đầy đủ nội thất đẹp.', 'Đầy đủ nội thất, nội thất cơ bản, căn hộ còn thô từ chủ đầu tư Novaland bàn giao', 'Đầy đủ nội thất, sang trọng.', 'Đầy đủ nội thất, tiện nghi.', 'Đầy đủ nội thất.', 'Đầy đủ nội thất: Tivi, tủ lạnh, máy giặt, điều hòa Daikin âm trần inverter, nóng lạnh, giường tủ, sofa, hệ thống bếp, tủ bếp trên dưới, tủ âm tường, sàn gỗ, thiết bị vệ sinh...', 'Đầy đủ trang bị đầy đủ nội thất như điều hòa, tủ lạnh, giường.', 'Đầy đủ điều hòa, giường, tủ lạnh...', 'Đầy đủ đầy đủ nội thất.', 'Đầy đủ đồ chỉ thiếu chủ mới.', 'Đầy đủ đồ.', 'Đầy đủ.', 'Đầy đủ. Căn trang bị đầy đủ nội thất.', 'Đầy đủ. Nội thất căn hộ: Hệ thống đèn chiếu sáng sang trọng, điều hòa âm trần, sàn gỗ, tủ âm tường, bếp, tủ bếp và các thiết bị vệ sinh cao cấp...', 'Đầy đủ. Tủ bếp, bếp từ hút mùi, lò vi sóng âm tủ, tủ lạnh, sofa, bàn ăn, giường tủ, điều hòa, rèm.', 'Để lại hết nội thất.', 'Để lại nội thất.', 'Đồ cơ bản của chủ đầu tư.', 'Đủ nội thất.']

 legal_status
['+ Sổ đỏ chính chủ.', '- Pháp lý sổ hồng lâu dài.', '- Sở hữu vĩnh viễn.', 'Bán căn hộ 3pn tòa M3, DT 115m2', 'Chuẩn bị ra sổ.', 'Có sổ', 'Có sổ ( sử dụng chung)', 'Có sổ hồng', 'Có sổ hồng.', 'Có sổ( sử dụng chung).', 'Có sổ.', 'Giấy tờ pháp lý', 'HDDC', 'HDMB', 'HĐMB', 'HĐMB, giỏ hàng độc quyền', 'HĐMB.', 'Hđmb', 'Hợp đồng mua bán', 'Hợp đồng coch', 'Hợp đồng cọc', 'Hợp đồng mua bán', 'Hợp đồng mua bán.', 'Hợp đồng đặt cọc', 'Nhà tôi sẵn sổ đỏ giao dịch.', 'Pháp lí rõ ràng.', 'Sổ đỏ/ Sổ hồng', 'Sẵn sổ hồng', 'Sổ hồng', 'Sổ hồng chính chủ', 'Sổ hồng chính chủ.', 'Sổ hồng giấy chứng nhận quyền sử dụng đất.', 'Sổ hồng lâu dài', 'Sổ hồng riêng.', 'Sổ hồng sẵn.', 'Sổ hồng.', 'Sổ sẵn công chứng, không vay', 'Sổ sẵn đang vay bank', 'Sổ đỏ', 'Sổ đỏ ( sử dụng chung)', 'Sổ đỏ chính chủ.', 'Sổ đỏ cầm tay', 'Sổ đỏ cầm tay, giao dịch nhanh chóng', 'Sổ đỏ lâu dài.', 'Sổ đỏ.', 'Sổ đỏ/ Sổ hồng', 'Sổ đỏ/ Sổ hồng ( sử dụng chung)', 'Sổ đỏ/ Sổ hồng (sử dụng chung)', 'Sổ đỏ/ Sổ hồng (sử dụng chung).', 'Sổ đỏ/ Sổ hồng chung', 'Sổ đỏ/ Sổ hồng( sử dụng chung)', 'Sổ đỏ/ Sổ hồng.', 'Sổ đỏ/sổ hồng.', 'Văn Bản Thoả Thuận', 'Văn Bản Thỏa Thuận (ký HĐMB T3/2026)', 'Văn Bản Thỏa thuận, ký HDMB T3/2026', 'Văn bản thoã thuận', 'Văn bản thỏa thuận', 'nan', 'Đang chờ sổ', 'Đang chờ sổ.', 'Đang trong quá trình xây dựng', 'Đã có sổ', 'Đã có sổ hồng', 'Đã có sổ hồng.', 'Đã có sổ.', 'Đã sổ hồng', 'Đầy đủ']

 listing_type
['vip-diamond', 'vip-gold', 'vip-normal', 'vip-silver']

 ownership
['Chưa cấp sổ', 'Chưa cấp sổ đồng loạt', 'Sổ hồng', 'Sổ hồng lâu dài', 'Sổ đỏ không thời hạn', 'Sổ đỏ lâu dài', 'Sở hữu không thời hạn', 'Sở hữu lâu dài', 'Sở hữu lâu dài đối với khách hàng người Việt Nam. 50 năm đối với khách hàng người nước ngoài.']

In [ ]:
dir_map = {
    "Đông - Nam": "Đông Nam",
    "Đông - Bắc": "Đông Bắc",
    "Tây - Nam": "Tây Nam",
    "Tây - Bắc": "Tây Bắc"
}

merged_df["direction"] = merged_df["direction"].replace(dir_map)
merged_df["balcony_direction"] = merged_df["balcony_direction"].replace(dir_map)

In [ ]:
merged_df["furnishing"] = (
    merged_df["furnishing"]
    .astype(str)
    .str.lower()
    .str.strip()
)

In [ ]:
def map_furnishing(x):

    if pd.isna(x) or x == "nan":
        return None

    if any(k in x for k in [
        "đầy đủ", "full", "đủ nội thất", "nội thất đầy đủ"
    ]):
        return "Đầy đủ"

    elif any(k in x for k in [
        "cơ bản", "ntcb", "nội thất cơ bản"
    ]):
        return "Cơ bản"

    elif any(k in x for k in [
        "không nội thất", "bàn giao thô", "nhà trống"
    ]):
        return "Không nội thất"

    else:
        return "Cơ bản"

In [ ]:
merged_df["furnishing_clean"] = merged_df["furnishing"].apply(map_furnishing)

In [ ]:
merged_df["furnishing_clean"].value_counts(dropna=False)

furnishing_clean
Đầy đủ            2265
Cơ bản            1119
None               936
Không nội thất      89
Name: count, dtype: int64

In [ ]:
merged_df["furnishing"] = merged_df["furnishing_clean"]
merged_df.drop(columns="furnishing_clean", inplace=True)

In [ ]:
merged_df["legal_status"] = (
    merged_df["legal_status"]
    .astype(str)
    .str.lower()
    .str.strip()
)

In [ ]:
import pandas as pd

def map_legal_status(x):

    if pd.isna(x) or x == "nan":
        return None   # giữ NaN

    if any(k in x for k in [
        "sổ đỏ",
        "sổ hồng",
        "đã có sổ"
    ]):
        return "Sổ đỏ / Sổ hồng"

    elif any(k in x for k in [
        "hợp đồng mua bán",
        "hdmb",
        "hđmb"
    ]):
        return "Hợp đồng mua bán"

    elif any(k in x for k in [
        "chờ sổ",
        "đang chờ sổ",
        "chưa ra sổ"
    ]):
        return "Đang chờ sổ"

    else:
        return "Không rõ"

In [ ]:
merged_df["legal_status"] = merged_df["legal_status"].apply(map_legal_status)

In [ ]:
merged_df["legal_status"].value_counts(dropna=False)

legal_status
Sổ đỏ / Sổ hồng     2249
Hợp đồng mua bán    1234
None                 750
Đang chờ sổ          106
Không rõ              70
Name: count, dtype: int64

In [ ]:
merged_df["ownership"] = (
    merged_df["ownership"]
    .astype(str)
    .str.lower()
    .str.strip()
)

In [ ]:
import pandas as pd

def map_ownership(x):

    if pd.isna(x) or x == "nan":
        return None

    if any(k in x for k in [
        "lâu dài",
        "không thời hạn",
        "sổ hồng",
        "sổ đỏ"
    ]):
        return "Lâu dài"

    elif any(k in x for k in [
        "chưa cấp sổ",
        "chưa có sổ"
    ]):
        return "Chưa có sổ"

    else:
        return "Không rõ"

In [ ]:
merged_df["ownership"] = merged_df["ownership"].apply(map_ownership)

In [ ]:
merged_df["ownership"].value_counts(dropna=False)

ownership
Lâu dài       4186
Chưa có sổ     223
Name: count, dtype: int64

In [ ]:
merged_df.isna().sum().sort_values(ascending=False)

furnishing              936
legal_status            750
bathrooms               421
bedrooms                257
dist_metro_km            76
handover_year            42
num_towers               20
title                     0
project                   0
brand                     0
url                       0
city                      0
area_m2                   0
balcony_direction         0
direction                 0
expired_date              0
posted_date               0
description               0
listing_type              0
price_per_m2              0
price_vnd                 0
land_area_ha              0
admin_area                0
construction_density      0
total_apartment           0
Metro_city                0
dist_river_lake_km        0
dist_highway_km           0
dist_cbd_km               0
dist_airport_km           0
has_mall                  0
has_hospital              0
has_school                0
has_park                  0
has_pool                  0
launch_year               0
ownership                 0
dtype: int64

In [ ]:
merged_df["price_per_m2"].describe()

count    4.409000e+03
mean     8.811447e+07
std      4.330457e+07
min      0.000000e+00
25%      6.285714e+07
50%      7.928571e+07
75%      1.021591e+08
max      7.545455e+08
Name: price_per_m2, dtype: float64

In [ ]:
merged_df = merged_df[merged_df["price_per_m2"] > 0]

In [ ]:
merged_df = merged_df[
    (merged_df["price_vnd"] >= 200_000_000) &
    (merged_df["price_vnd"] <= 300_000_000_000)
]

In [ ]:
merged_df = merged_df[
    (merged_df["area_m2"] >= 20) &
    (merged_df["area_m2"] <= 500)
]

In [ ]:
merged_df = merged_df[
    (merged_df["price_per_m2"] >= 5_000_000) &
    (merged_df["price_per_m2"] <= 400_000_000)
]

In [ ]:
merged_df[["area_m2","price_vnd","price_per_m2"]].describe()

           area_m2     price_vnd  price_per_m2
count  4362.000000  4.362000e+03  4.362000e+03
mean     71.911985  6.817992e+09  8.876336e+07
std      31.695124  6.435653e+09  4.111175e+07
min      25.000000  4.499000e+08  6.079729e+06
25%      53.900000  3.600000e+09  6.333333e+07
50%      69.000000  4.800000e+09  7.959184e+07
75%      81.800000  7.900000e+09  1.025316e+08
max     400.000000  8.900000e+10  3.750000e+08

In [ ]:
merged_df = merged_df.reset_index(drop=True)

In [ ]:
merged_df["num_towers"] = pd.to_numeric(merged_df["num_towers"], errors="coerce")

In [ ]:
merged_df["bedrooms"] = merged_df["bedrooms"].astype("Int64")
merged_df["bathrooms"] = merged_df["bathrooms"].astype("Int64")

In [ ]:
bool_cols = [
"has_mall",
"has_school",
"has_hospital",
"has_park",
"has_pool",
"Metro_city"
]

merged_df[bool_cols] = merged_df[bool_cols].astype("bool")

In [ ]:
merged_df.dtypes

brand                           object
project                         object
city                            object
url                             object
title                           object
price_vnd                        int64
area_m2                        float64
price_per_m2                   float64
bedrooms                         Int64
bathrooms                        Int64
direction                       object
balcony_direction               object
furnishing                      object
legal_status                    object
posted_date             datetime64[ns]
expired_date            datetime64[ns]
description                     object
listing_type                    object
admin_area                      object
land_area_ha                   float64
num_towers                     float64
total_apartment                  int64
construction_density           float64
dist_cbd_km                    float64
dist_metro_km                  float64
Metro_city                        bool
dist_river_lake_km             float64
dist_highway_km                float64
dist_airport_km                float64
has_mall                          bool
has_school                        bool
has_hospital                      bool
has_park                          bool
has_pool                          bool
launch_year                      int64
handover_year                  float64
ownership                       object
dtype: object

In [ ]:
import pandas as pd
import unicodedata

# ===== NORMALIZE TEXT =====
def remove_accent(text):
    text = unicodedata.normalize('NFD', str(text))
    return ''.join(c for c in text if unicodedata.category(c) != 'Mn')

# ===== CITY =====
def normalize_city(city):
    if pd.isna(city):
        return "unknown"

    city = str(city).lower().strip()
    city = remove_accent(city)

    if any(x in city for x in ["hcm", "ho chi minh", "tphcm", "tp hcm", "sai gon"]):
        return "hcm"

    if any(x in city for x in ["ha noi", "hanoi", "hn"]):
        return "hn"

    if any(x in city for x in ["da nang", "danang"]):
        return "danang"

    return city


# ===== BRAND =====
def normalize_brand(brand):
    if pd.isna(brand):
        return "unknown"

    brand = str(brand).lower()

    if "vin" in brand:
        return "vinhomes"

    return brand


# ===== APPLY =====
merged_df = merged_df.copy()

merged_df["city"] = merged_df["city"].apply(normalize_city)
merged_df["brand"] = merged_df["brand"].apply(normalize_brand)

# ===== FIX PRICE =====
merged_df["price_vnd"] = merged_df["price_vnd"].fillna(0).astype(float).round().astype("int64")

# ===== OTHER NUMERIC =====
merged_df["area_m2"] = merged_df["area_m2"].astype(float)
merged_df["bedrooms"] = merged_df["bedrooms"].fillna(0).astype(int)
merged_df["bathrooms"] = merged_df["bathrooms"].fillna(0).astype(int)

# ===== OPTIONAL =====
if "project_name" in merged_df.columns:
    merged_df["project_name"] = merged_df["project_name"].str.lower().str.strip()

# ===== CHECK =====
print(merged_df[["city", "brand"]].drop_duplicates().head())
print(merged_df.dtypes)

          city     brand
0           hn  vinhomes
49         hcm  novaland
110        hcm  vinhomes
122  thanh hoa  vinhomes
150   bac ninh  vinhomes
brand                           object
project                         object
city                            object
url                             object
title                           object
price_vnd                        int64
area_m2                        float64
price_per_m2                   float64
bedrooms                         int64
bathrooms                        int64
direction                       object
balcony_direction               object
furnishing                      object
legal_status                    object
posted_date             datetime64[ns]
expired_date            datetime64[ns]
description                     object
listing_type                    object
admin_area                      object
land_area_ha                   float64
num_towers                     float64
total_apartment                  int64
construction_density           float64
dist_cbd_km                    float64
dist_metro_km                  float64
Metro_city                        bool
dist_river_lake_km             float64
dist_highway_km                float64
dist_airport_km                float64
has_mall                          bool
has_school                        bool
has_hospital                      bool
has_park                          bool
has_pool                          bool
launch_year                      int64
handover_year                  float64
ownership                       object
dtype: object

In [ ]:
merged_df.to_parquet(
    "Batdongsan_clean_ver1.parquet",
    index=False
)

In [ ]:
merged_df["price_vnd"] = merged_df["price_vnd"].astype("int64")
merged_df.to_csv(
    "Batdongsan_clean_ver1.csv",
    index=False
)